Feature/amqp connection
jortiz3109/escuela-php-messaging pull request #4
Opened 2021-10-05 03:06 UTC by FrederST

AQMPConnection Implementation

2021-10-06 14:22 UTC, VictorMonroyHz approved these changes

2021-10-06 15:30 UTC, jortiz3109 requested changes

2021-10-06 15:30 UTC, jortiz3109 commented on composer.json
> +    "description": "RabbitMQ Message",
¿Esta si es una descripción idónea para el paquete?

2021-10-06 15:30 UTC, jortiz3109 commented on config/amqp.php
> +        'host' => env('AMQP_HOST', 'beaver.rmq.cloudamqp.com'),
¿Porque por defecto buscamos un host que podría no ser accesible?
¿No sería mas idóneo tratar de buscar la misma implementación pero en localhost?

2021-10-06 15:30 UTC, jortiz3109 commented on config/amqp.php
> +        'password' => env('AMQP_PASSWORD', 'RExuiTPwf0ZxH68RLQoqBlodnMheoSfi'),
NO es una buena práctica almacenar datos de login (usuarios y contraseñas) en el código fuente de una aplicación.

De hecho, esta pieza de código levantaría una no-conformidad en una auditoría PCI

2021-10-06 15:30 UTC, jortiz3109 commented on config/amqp.php
> +        'vhost' => env('AMQP_VHOST', 'pzrjdqgp'),
El protocolo AMQP tiene unos datos por defecto para el host, creo que sería mas idóneo usar esos datos por defecto.

2021-10-06 15:30 UTC, jortiz3109 commented on config/amqp.php
> +        'name' => env('AMQP_EXCHANGE_NAME', 'payment_exchange'),
Creo que el exchange payment_exchange es un exchange muy específico y no debería ser un valor por defecto.

2021-10-06 15:30 UTC, jortiz3109 commented on src/AMQPConnection.php
> +use Illuminate\Support\Arr;
Si vamos a utilizar un Helper de Laravel, deberíamos incluir Illuminate/Support como dependencia

2021-10-06 15:30 UTC, jortiz3109 commented on src/AMQPConnection.php
> +            if (!is_null($this->config)) {
¿En que caso se daría que la configuración fuera null?
Creo que este if nos daría mas problemas que soluciones en un futuro

2021-10-06 15:30 UTC, jortiz3109 commented on src/AMQPConnection.php
> +            if (!is_null($this->config)) {
Adicional, la propiedad está marcada como array, no entiendo en que situaciones obtendríamos un null

2021-10-06 15:30 UTC, jortiz3109 commented on src/AMQPConnection.php
> +                Arr::get($this->config, 'ssl', true)
¿Aquí no podríamos aplicar un patrón para usar composición en lugar de sobrecargar la clase con múltiples métodos de conexión?

2021-10-06 15:30 UTC, jortiz3109 commented on src/AMQPConnection.php
> +                throw new AMQPConnectionException('Error -> Please publish the config file by running php artisan vendor:publish --tag=amqp-config');
Si tienes que lanzar esta excepción, es porque tu paquete no está cargando la configuración, esto no debería suceder.

2021-10-06 15:30 UTC, jortiz3109 commented on src/AMQPConnection.php
> +                throw new AMQPConnectionException('Error -> Please publish the config file by running php artisan vendor:publish --tag=amqp-config');
De hecho, la publicación de la configuración debería ser un paso completamente opcional

2021-10-06 15:30 UTC, jortiz3109 commented on src/Exceptions/AMQPConnectionException.php
> +<?php
¿Si es necesaria esta excepción teniendo en cuenta que la librería amqp ya tiene una?

2021-10-06 15:30 UTC, jortiz3109 commented on src/Providers/MessagingServiceProvider.php
> +    public function boot()
¿Y el tipo de dato de retorno?

2021-10-06 15:30 UTC, jortiz3109 commented on src/Providers/MessagingServiceProvider.php
> +    public function register()
¿Y el tipo de dato de retorno?

2021-10-06 15:30 UTC, jortiz3109 commented on src/Providers/MessagingServiceProvider.php
> +    protected function registerPublishing()
¿Y el tipo de dato de retorno?

2021-10-06 15:30 UTC, jortiz3109 commented on src/Providers/MessagingServiceProvider.php
> +    protected function registerResources()
¿Y el tipo de dato de retorno?

2021-10-11 23:30 UTC, ragallegom approved these changes

2021-10-11 23:31 UTC, Johnja85 approved these changes

2021-10-11 23:33 UTC, xfchris approved these changes

2021-10-11 23:33 UTC, xfchris commented on composer.json
>              "Messaging\\": "src/"
El nombre del paquete debe ser E4/Messaging

2021-10-11 23:33 UTC, xfchris commented on composer.json
> +        "php": "^7.3 | ^8.0",
Para comodidad de jhon, mejor usar 7.4 en adelante

2021-10-11 23:33 UTC, xfchris commented on src/AMQPConnection.php
> +<?php
Comentar las funciones de la clase

2021-10-14 23:49 UTC, merged